name: Build

on: [pull_request, push, repository_dispatch]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arduino-platform:
          - 'feather_rp2040'
          - 'metro_m0'
          - 'metro_m4'
          - 'nrf52840'
          - 'metroesp32s2'

    runs-on: ubuntu-latest
    steps:
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
        
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Checkout adafruit/ci-arduino
      uses: actions/checkout@v3
      with:
         repository: adafruit/ci-arduino
         path: ci

    - name: pre-install
      run: bash ci/actions_install.sh

    - name: test platforms
      run: python3 ci/build_platform.py ${{ matrix.arduino-platform }}
